<!DOCTYPE HTML>
<html>

    <head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<meta name="description" content="LBS MFA 2021 Stream B">
	<meta name="author" content="Xiaoqi Pan">
	<meta name="generator" content="Hugo 0.76.3" />
	<title>Airbnb &middot; Portfolio website for Xiaoqi Pan</title>
	<!-- Stylesheets -->
	
	<link rel="stylesheet" href="/css/main.css"/>
	
	

	

	<!-- Custom Fonts -->
	<link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
	<link rel="icon" type="image/x-icon" href="/favicon.ico">
	

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="js/ie/html5shiv.js"></script>
	<script src="js/ie/html5shiv.jsrespond.min.js"></script>
	<![endif]-->
</head>

    <body>

    <!-- Wrapper -->
        <div id="wrapper">

            <!-- Header -->
    <header id="header" class="alt">
        <a href="/" class="logo"><strong> Xiaoqi Pan</strong> <span>Welcome to My Website</span></a>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>

<!-- Menu -->
    <nav id="menu">
        <ul class="links">
            
                <li><a href="/">Home</a></li>
            
                <li><a href="/blogs">Blogs</a></li>
            
                <li><a href="/blogs/ipsum">Generic Blog</a></li>
            
                <li><a href="/elements.html">Elements</a></li>
            

        </ul>
        <ul class="actions vertical">
            
                <li><a href="/blogs" class="button special fit">Get Started</a></li>
            
            
                <li><a href="/" class="button fit">Log In</a></li>
            
        </ul>
    </nav>

        <!-- Main -->
            <div id="main" class="alt">

                
                    <section id="one">
                        <div class="inner">
                            <header class="major">
                                <h1>Airbnb</h1>
                            </header>
                            
                            <h1 id="introduction-data-methods">Introduction, Data, Methods</h1>
<p>In this project, we are going to analyse data about Airbnb listings and fit a model to predict the total cost for two people staying 4 nights in an Airbnb in a city. Our data comes from <a href="insideairbnb.com">insideairbnb.com</a>; it was originally scraped from airbnb.com.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e"># Load data</span>
listings <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">vroom</span>(<span style="color:#e6db74">&#34;http://data.insideairbnb.com/belgium/bru/brussels/2020-06-15/data/listings.csv.gz&#34;</span>)
</code></pre></div><p>Some important variables are as follows:</p>
<ul>
<li><code>price</code> : cost per night</li>
<li><code>cleaning_fee</code>: cleaning fee</li>
<li><code>extra_people</code>: charge for having 1 more person</li>
<li><code>property_type</code>: type of accommocation (House, Apartment, etc.)</li>
<li><code>room_type</code>: Entire home, Private room, Shared room</li>
<li><code>number_of_reviews</code>: Total number of reviews for the listing</li>
<li><code>review_scores_rating</code>: Average review score (0-100)</li>
<li><code>longtitude</code>, <code>latitude</code>: geographical coordinates to help us locate the listing</li>
<li><code>neighbourhood*</code>: three variables on a few major neighbourboods in each city</li>
</ul>
<p>Firstly, we start with a map of Brussels, and overlay all Airbnb coordinates to get an overview of the spatial distribution of Airbnb rentals. For this visualization, we use <code>leaflet</code> package, which includes a variety of tools for interactive maps.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">leaflet</span>(data <span style="color:#f92672">=</span> <span style="color:#a6e22e">filter</span>(listings,minimum_nights<span style="color:#f92672">&lt;=</span><span style="color:#ae81ff">4</span>)) <span style="color:#f92672">%&gt;%</span> 
  <span style="color:#a6e22e">addProviderTiles</span>(<span style="color:#e6db74">&#34;OpenStreetMap.Mapnik&#34;</span>) <span style="color:#f92672">%&gt;%</span> 
  <span style="color:#a6e22e">addCircleMarkers</span>(lng <span style="color:#f92672">=</span> <span style="color:#f92672">~</span>longitude, 
                   lat <span style="color:#f92672">=</span> <span style="color:#f92672">~</span>latitude, 
                   radius <span style="color:#f92672">=</span> <span style="color:#ae81ff">1</span>, 
                   fillColor <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;blue&#34;</span>, 
                   fillOpacity <span style="color:#f92672">=</span> <span style="color:#ae81ff">0.4</span>, 
                   popup <span style="color:#f92672">=</span> <span style="color:#f92672">~</span>listing_url,
                   label <span style="color:#f92672">=</span> <span style="color:#f92672">~</span>property_type)
</code></pre></div><p>preserve574fb325c6982f2e</p>
<h1 id="data-wrangling-and-exploratory-data-analysis-eda">Data Wrangling and Exploratory Data Analysis (EDA)</h1>
<h2 id="data-wrangling">Data Wrangling</h2>
<p>Some of the price data (<code>price</code>, <code>cleaning_fee</code>, <code>extra_people</code>) is given as a character string. Since what we want is a quantitative variable, we need to make sure it is stored as numeric data <code>num</code> in the dataframe. To do so, we will first use <code>readr::parse_number()</code> which drops any non-numeric characters before or after the first number.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">listings <span style="color:#f92672">&lt;-</span> listings <span style="color:#f92672">%&gt;%</span> 
  <span style="color:#a6e22e">mutate</span>(price <span style="color:#f92672">=</span> <span style="color:#a6e22e">parse_number</span>(price)) <span style="color:#f92672">%&gt;%</span> 
  <span style="color:#a6e22e">mutate</span>(cleaning_fee<span style="color:#f92672">=</span> <span style="color:#a6e22e">parse_number</span>(cleaning_fee)) <span style="color:#f92672">%&gt;%</span> 
  <span style="color:#a6e22e">mutate</span>(extra_people<span style="color:#f92672">=</span> <span style="color:#a6e22e">parse_number</span>(extra_people))

<span style="color:#a6e22e">typeof</span>(listings<span style="color:#f92672">$</span>price)
</code></pre></div><pre><code>## [1] &quot;double&quot;
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">typeof</span>(listings<span style="color:#f92672">$</span>cleaning_fee)
</code></pre></div><pre><code>## [1] &quot;double&quot;
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">typeof</span>(listings<span style="color:#f92672">$</span>extra_people)
</code></pre></div><pre><code>## [1] &quot;double&quot;
</code></pre><p>We then impute the missing values of <code>cleaning_fee</code> with an appropriate numeric value.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">listings <span style="color:#f92672">&lt;-</span> listings <span style="color:#f92672">%&gt;%</span>
  <span style="color:#a6e22e">mutate</span>(cleaning_fee <span style="color:#f92672">=</span> <span style="color:#a6e22e">case_when</span>(
    <span style="color:#a6e22e">is.na</span>(cleaning_fee) <span style="color:#f92672">~</span> <span style="color:#ae81ff">0</span>, 
    <span style="color:#66d9ef">TRUE</span> <span style="color:#f92672">~</span> cleaning_fee
  ))
</code></pre></div><p>Next, we look at the variable <code>property_type</code>. Since the vast majority of the observations in the data are one of the top four of five property types, we would like to create a simplified version of <code>property_type</code> variable that has 5 catergories: the top four categories and <code>Other</code>.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">listings <span style="color:#f92672">&lt;-</span> listings <span style="color:#f92672">%&gt;%</span>
  <span style="color:#a6e22e">mutate</span>(prop_type_simplified <span style="color:#f92672">=</span> <span style="color:#a6e22e">case_when</span>(
    property_type <span style="color:#f92672">%in%</span> <span style="color:#a6e22e">c</span>(<span style="color:#e6db74">&#34;Apartment&#34;</span>,<span style="color:#e6db74">&#34;House&#34;</span>, <span style="color:#e6db74">&#34;Condominium&#34;</span>,<span style="color:#e6db74">&#34;Townhouse&#34;</span>) <span style="color:#f92672">~</span> property_type, 
    <span style="color:#66d9ef">TRUE</span> <span style="color:#f92672">~</span> <span style="color:#e6db74">&#34;Other&#34;</span>
  ))
</code></pre></div><p>Airbnb is most commonly used for travel purposes, i.e., as an alternative to traditional hotels. We only want to include listings in our regression analysis that are intended for travel purposes. We first use <code>skimr::skim()</code> to get an overview of <code>minimum_nights</code>. Most observations are lower than 4, with some extreme large values. To mitigate the influence of these outliers, we filter the airbnb data so that it only include observations with <code>minimum_nights&lt;=4</code></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">skim</span>(listings<span style="color:#f92672">$</span>minimum_nights)
</code></pre></div><p>Table: Data summary</p>
<table>
<thead>
<tr>
<th style="text-align:left"></th>
<th style="text-align:left"></th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">Name</td>
<td style="text-align:left">listings$minimum_nights</td>
</tr>
<tr>
<td style="text-align:left">Number of rows</td>
<td style="text-align:left">8986</td>
</tr>
<tr>
<td style="text-align:left">Number of columns</td>
<td style="text-align:left">1</td>
</tr>
<tr>
<td style="text-align:left">_______________________</td>
<td style="text-align:left"></td>
</tr>
<tr>
<td style="text-align:left">Column type frequency:</td>
<td style="text-align:left"></td>
</tr>
<tr>
<td style="text-align:left">numeric</td>
<td style="text-align:left">1</td>
</tr>
<tr>
<td style="text-align:left">________________________</td>
<td style="text-align:left"></td>
</tr>
<tr>
<td style="text-align:left">Group variables</td>
<td style="text-align:left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left">skim_variable</th>
<th style="text-align:right">n_missing</th>
<th style="text-align:right">complete_rate</th>
<th style="text-align:right">mean</th>
<th style="text-align:right">sd</th>
<th style="text-align:right">p0</th>
<th style="text-align:right">p25</th>
<th style="text-align:right">p50</th>
<th style="text-align:right">p75</th>
<th style="text-align:right">p100</th>
<th style="text-align:left">hist</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">data</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">7.4</td>
<td style="text-align:right">29.2</td>
<td style="text-align:right">1</td>
<td style="text-align:right">1</td>
<td style="text-align:right">2</td>
<td style="text-align:right">3</td>
<td style="text-align:right">1000</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">listings <span style="color:#f92672">&lt;-</span> listings <span style="color:#f92672">%&gt;%</span> 
  <span style="color:#a6e22e">filter</span>(minimum_nights <span style="color:#f92672">&lt;=</span> <span style="color:#ae81ff">4</span>)
</code></pre></div><p>We drop some variables and only keep some necessary ones in our analysis. We then skim the dataset to see if further data wrangling is required.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">listings_selected <span style="color:#f92672">&lt;-</span> listings <span style="color:#f92672">%&gt;%</span> 
  <span style="color:#a6e22e">select</span>(<span style="color:#e6db74">&#34;id&#34;</span>, <span style="color:#e6db74">&#34;price&#34;</span>, <span style="color:#e6db74">&#34;cleaning_fee&#34;</span>, <span style="color:#e6db74">&#34;extra_people&#34;</span>, <span style="color:#e6db74">&#34;prop_type_simplified&#34;</span>, <span style="color:#e6db74">&#34;room_type&#34;</span>, <span style="color:#e6db74">&#34;minimum_nights&#34;</span>, <span style="color:#e6db74">&#34;guests_included&#34;</span>, <span style="color:#e6db74">&#34;number_of_reviews&#34;</span>, <span style="color:#e6db74">&#34;review_scores_rating&#34;</span>, <span style="color:#e6db74">&#34;longitude&#34;</span>, <span style="color:#e6db74">&#34;latitude&#34;</span>, <span style="color:#e6db74">&#34;neighbourhood&#34;</span>,<span style="color:#e6db74">&#34;neighbourhood_cleansed&#34;</span>, <span style="color:#e6db74">&#34;listing_url&#34;</span>,<span style="color:#e6db74">&#34;bathrooms&#34;</span>,<span style="color:#e6db74">&#34;bedrooms&#34;</span>,<span style="color:#e6db74">&#34;beds&#34;</span>,<span style="color:#e6db74">&#34;accommodates&#34;</span>,<span style="color:#e6db74">&#34;host_is_superhost&#34;</span>,<span style="color:#e6db74">&#34;is_location_exact&#34;</span>,<span style="color:#e6db74">&#34;cancellation_policy&#34;</span>) 

<span style="color:#a6e22e">glimpse</span>(listings_selected)
</code></pre></div><pre><code>## Rows: 7,279
## Columns: 22
## $ id                     &lt;dbl&gt; 2352, 2354, 45145, 48180, 71744, 80257, 80320,…
## $ price                  &lt;dbl&gt; 93, 78, 100, 200, 60, 95, 85, 85, 135, 70, 85,…
## $ cleaning_fee           &lt;dbl&gt; 65, 65, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 60, 0, …
## $ extra_people           &lt;dbl&gt; 5, 0, 30, 20, 15, 20, 10, 10, 25, 20, 10, 45, …
## $ prop_type_simplified   &lt;chr&gt; &quot;Apartment&quot;, &quot;Apartment&quot;, &quot;Other&quot;, &quot;Apartment&quot;…
## $ room_type              &lt;chr&gt; &quot;Entire home/apt&quot;, &quot;Entire home/apt&quot;, &quot;Hotel r…
## $ minimum_nights         &lt;dbl&gt; 2, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 1…
## $ guests_included        &lt;dbl&gt; 4, 1, 1, 1, 2, 2, 2, 2, 4, 2, 2, 1, 1, 2, 2, 2…
## $ number_of_reviews      &lt;dbl&gt; 15, 2, 3, 0, 12, 4, 59, 6, 48, 25, 33, 3, 1, 4…
## $ review_scores_rating   &lt;dbl&gt; 87, 80, 100, NA, 98, 90, 93, 97, 87, 91, 92, 9…
## $ longitude              &lt;dbl&gt; 4.31, 4.31, 4.37, 4.41, 4.35, 4.34, 4.34, 4.34…
## $ latitude               &lt;dbl&gt; 50.9, 50.9, 50.9, 50.8, 50.9, 50.8, 50.8, 50.8…
## $ neighbourhood          &lt;chr&gt; &quot;Molenbeek-Saint-Jean&quot;, &quot;Molenbeek-Saint-Jean&quot;…
## $ neighbourhood_cleansed &lt;chr&gt; &quot;Molenbeek-Saint-Jean&quot;, &quot;Molenbeek-Saint-Jean&quot;…
## $ listing_url            &lt;chr&gt; &quot;https://www.airbnb.com/rooms/2352&quot;, &quot;https://…
## $ bathrooms              &lt;dbl&gt; 1.0, 1.0, 1.0, 1.5, 1.0, 1.0, 1.0, 1.0, 2.0, 1…
## $ bedrooms               &lt;dbl&gt; 2, 1, 1, 2, 1, 0, 0, 0, 1, 0, 1, 2, 1, 0, 1, 0…
## $ beds                   &lt;dbl&gt; 2, 1, 1, 2, 1, 2, 2, 2, 4, 2, 3, 3, 1, 2, 1, 2…
## $ accommodates           &lt;dbl&gt; 5, 4, 2, 2, 2, 3, 3, 3, 6, 3, 4, 4, 2, 3, 2, 3…
## $ host_is_superhost      &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALS…
## $ is_location_exact      &lt;lgl&gt; TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRU…
## $ cancellation_policy    &lt;chr&gt; &quot;strict_14_with_grace_period&quot;, &quot;strict_14_with…
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">skim</span>(listings_selected)
</code></pre></div><p>Table: Data summary</p>
<table>
<thead>
<tr>
<th style="text-align:left"></th>
<th style="text-align:left"></th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">Name</td>
<td style="text-align:left">listings_selected</td>
</tr>
<tr>
<td style="text-align:left">Number of rows</td>
<td style="text-align:left">7279</td>
</tr>
<tr>
<td style="text-align:left">Number of columns</td>
<td style="text-align:left">22</td>
</tr>
<tr>
<td style="text-align:left">_______________________</td>
<td style="text-align:left"></td>
</tr>
<tr>
<td style="text-align:left">Column type frequency:</td>
<td style="text-align:left"></td>
</tr>
<tr>
<td style="text-align:left">character</td>
<td style="text-align:left">6</td>
</tr>
<tr>
<td style="text-align:left">logical</td>
<td style="text-align:left">2</td>
</tr>
<tr>
<td style="text-align:left">numeric</td>
<td style="text-align:left">14</td>
</tr>
<tr>
<td style="text-align:left">________________________</td>
<td style="text-align:left"></td>
</tr>
<tr>
<td style="text-align:left">Group variables</td>
<td style="text-align:left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left">skim_variable</th>
<th style="text-align:right">n_missing</th>
<th style="text-align:right">complete_rate</th>
<th style="text-align:right">min</th>
<th style="text-align:right">max</th>
<th style="text-align:right">empty</th>
<th style="text-align:right">n_unique</th>
<th style="text-align:right">whitespace</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">prop_type_simplified</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">5</td>
<td style="text-align:right">11</td>
<td style="text-align:right">0</td>
<td style="text-align:right">5</td>
<td style="text-align:right">0</td>
</tr>
<tr>
<td style="text-align:left">room_type</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">10</td>
<td style="text-align:right">15</td>
<td style="text-align:right">0</td>
<td style="text-align:right">4</td>
<td style="text-align:right">0</td>
</tr>
<tr>
<td style="text-align:left">neighbourhood</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">5</td>
<td style="text-align:right">21</td>
<td style="text-align:right">0</td>
<td style="text-align:right">49</td>
<td style="text-align:right">0</td>
</tr>
<tr>
<td style="text-align:left">neighbourhood_cleansed</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">5</td>
<td style="text-align:right">21</td>
<td style="text-align:right">0</td>
<td style="text-align:right">19</td>
<td style="text-align:right">0</td>
</tr>
<tr>
<td style="text-align:left">listing_url</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">33</td>
<td style="text-align:right">37</td>
<td style="text-align:right">0</td>
<td style="text-align:right">7279</td>
<td style="text-align:right">0</td>
</tr>
<tr>
<td style="text-align:left">cancellation_policy</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">8</td>
<td style="text-align:right">27</td>
<td style="text-align:right">0</td>
<td style="text-align:right">5</td>
<td style="text-align:right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: logical</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left">skim_variable</th>
<th style="text-align:right">n_missing</th>
<th style="text-align:right">complete_rate</th>
<th style="text-align:right">mean</th>
<th style="text-align:left">count</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">host_is_superhost</td>
<td style="text-align:right">3</td>
<td style="text-align:right">1</td>
<td style="text-align:right">0.18</td>
<td style="text-align:left">FAL: 5961, TRU: 1315</td>
</tr>
<tr>
<td style="text-align:left">is_location_exact</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">0.84</td>
<td style="text-align:left">TRU: 6079, FAL: 1200</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left">skim_variable</th>
<th style="text-align:right">n_missing</th>
<th style="text-align:right">complete_rate</th>
<th style="text-align:right">mean</th>
<th style="text-align:right">sd</th>
<th style="text-align:right">p0</th>
<th style="text-align:right">p25</th>
<th style="text-align:right">p50</th>
<th style="text-align:right">p75</th>
<th style="text-align:right">p100</th>
<th style="text-align:left">hist</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">id</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">2.50e+07</td>
<td style="text-align:right">1.29e+07</td>
<td style="text-align:right">2352.00</td>
<td style="text-align:right">1.39e+07</td>
<td style="text-align:right">2.60e+07</td>
<td style="text-align:right">3.71e+07</td>
<td style="text-align:right">4.38e+07</td>
<td style="text-align:left">▅▅▅▅▇</td>
</tr>
<tr>
<td style="text-align:left">price</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">7.83e+01</td>
<td style="text-align:right">1.17e+02</td>
<td style="text-align:right">0.00</td>
<td style="text-align:right">4.20e+01</td>
<td style="text-align:right">6.00e+01</td>
<td style="text-align:right">8.90e+01</td>
<td style="text-align:right">7.00e+03</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
<tr>
<td style="text-align:left">cleaning_fee</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">1.88e+01</td>
<td style="text-align:right">2.36e+01</td>
<td style="text-align:right">0.00</td>
<td style="text-align:right">0.00e+00</td>
<td style="text-align:right">1.20e+01</td>
<td style="text-align:right">3.00e+01</td>
<td style="text-align:right">5.05e+02</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
<tr>
<td style="text-align:left">extra_people</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">7.81e+00</td>
<td style="text-align:right">1.24e+01</td>
<td style="text-align:right">0.00</td>
<td style="text-align:right">0.00e+00</td>
<td style="text-align:right">0.00e+00</td>
<td style="text-align:right">1.50e+01</td>
<td style="text-align:right">2.69e+02</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
<tr>
<td style="text-align:left">minimum_nights</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">1.87e+00</td>
<td style="text-align:right">8.90e-01</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">2.00e+00</td>
<td style="text-align:right">2.00e+00</td>
<td style="text-align:right">4.00e+00</td>
<td style="text-align:left">▇▇▁▃▁</td>
</tr>
<tr>
<td style="text-align:left">guests_included</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">1.53e+00</td>
<td style="text-align:right">1.05e+00</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">2.00e+00</td>
<td style="text-align:right">1.60e+01</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
<tr>
<td style="text-align:left">number_of_reviews</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">3.45e+01</td>
<td style="text-align:right">6.62e+01</td>
<td style="text-align:right">0.00</td>
<td style="text-align:right">2.00e+00</td>
<td style="text-align:right">9.00e+00</td>
<td style="text-align:right">3.40e+01</td>
<td style="text-align:right">7.66e+02</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
<tr>
<td style="text-align:left">review_scores_rating</td>
<td style="text-align:right">1223</td>
<td style="text-align:right">0.83</td>
<td style="text-align:right">9.27e+01</td>
<td style="text-align:right">8.52e+00</td>
<td style="text-align:right">20.00</td>
<td style="text-align:right">9.00e+01</td>
<td style="text-align:right">9.50e+01</td>
<td style="text-align:right">9.80e+01</td>
<td style="text-align:right">1.00e+02</td>
<td style="text-align:left">▁▁▁▁▇</td>
</tr>
<tr>
<td style="text-align:left">longitude</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">4.36e+00</td>
<td style="text-align:right">3.00e-02</td>
<td style="text-align:right">4.26</td>
<td style="text-align:right">4.34e+00</td>
<td style="text-align:right">4.36e+00</td>
<td style="text-align:right">4.38e+00</td>
<td style="text-align:right">4.49e+00</td>
<td style="text-align:left">▁▆▇▂▁</td>
</tr>
<tr>
<td style="text-align:left">latitude</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">5.08e+01</td>
<td style="text-align:right">2.00e-02</td>
<td style="text-align:right">50.77</td>
<td style="text-align:right">5.08e+01</td>
<td style="text-align:right">5.08e+01</td>
<td style="text-align:right">5.09e+01</td>
<td style="text-align:right">5.09e+01</td>
<td style="text-align:left">▁▂▇▃▁</td>
</tr>
<tr>
<td style="text-align:left">bathrooms</td>
<td style="text-align:right">3</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">1.18e+00</td>
<td style="text-align:right">5.80e-01</td>
<td style="text-align:right">0.00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">3.00e+01</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
<tr>
<td style="text-align:left">bedrooms</td>
<td style="text-align:right">27</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">1.21e+00</td>
<td style="text-align:right">8.60e-01</td>
<td style="text-align:right">0.00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">3.00e+01</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
<tr>
<td style="text-align:left">beds</td>
<td style="text-align:right">77</td>
<td style="text-align:right">0.99</td>
<td style="text-align:right">1.74e+00</td>
<td style="text-align:right">1.33e+00</td>
<td style="text-align:right">0.00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">2.00e+00</td>
<td style="text-align:right">3.10e+01</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
<tr>
<td style="text-align:left">accommodates</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">3.08e+00</td>
<td style="text-align:right">1.77e+00</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">2.00e+00</td>
<td style="text-align:right">2.00e+00</td>
<td style="text-align:right">4.00e+00</td>
<td style="text-align:right">1.60e+01</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
<p>As we can see, <code>review_scores_rating</code>, <code>bathrooms</code>, <code>bedrooms</code>, and <code>beds</code> still have missing values. We will replace missing values of <code>review_scores_rating</code> with average <code>review_scores_rating</code>. As for <code>bathrooms</code>, <code>bedrooms</code>, and <code>beds</code>, we drop missing values. Price variables (<code>price</code>,<code>cleaning_fee</code>,<code>extra_people</code>) obviously skew to the right. When putting these values into our regression model, we will take logrithm.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">temp<span style="color:#f92672">=</span><span style="color:#a6e22e">mean</span>(listings_selected<span style="color:#f92672">$</span>review_scores_rating,na.rm<span style="color:#f92672">=</span><span style="color:#66d9ef">TRUE</span>)

listings_selected<span style="color:#f92672">&lt;-</span>listings_selected <span style="color:#f92672">%&gt;%</span>
  <span style="color:#a6e22e">mutate</span>(review_scores_rating<span style="color:#f92672">=</span><span style="color:#a6e22e">case_when</span>(
    <span style="color:#a6e22e">is.na</span>(review_scores_rating) <span style="color:#f92672">~</span> temp,
    <span style="color:#66d9ef">TRUE</span> <span style="color:#f92672">~</span> review_scores_rating
  ))

listings_selected<span style="color:#f92672">&lt;-</span>listings_selected <span style="color:#f92672">%&gt;%</span>
  <span style="color:#a6e22e">drop_na</span>(bathrooms,bedrooms,beds)
</code></pre></div><p>Up to now, we have already dealt with missing data and outliers. Next, we are going to create a new variable called <code>price_4_nights</code> that uses <code>price</code>, <code>cleaning_fee</code>, <code>guests_included</code>, and <code>extra_people</code> to calculate the total cost for two people to stay at the Airbnb property for 4 nights. This is the variable Y we want to explain.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">listings_selected <span style="color:#f92672">&lt;-</span> listings_selected <span style="color:#f92672">%&gt;%</span> 
  <span style="color:#a6e22e">mutate</span>(price_4_nights <span style="color:#f92672">=</span> <span style="color:#a6e22e">case_when</span>(
    guests_included <span style="color:#f92672">&gt;=</span> <span style="color:#ae81ff">2</span> <span style="color:#f92672">~</span> (cleaning_fee <span style="color:#f92672">+</span> price)<span style="color:#f92672">*</span><span style="color:#ae81ff">4</span>, 
    <span style="color:#66d9ef">TRUE</span> <span style="color:#f92672">~</span> (cleaning_fee <span style="color:#f92672">+</span> price <span style="color:#f92672">+</span> extra_people)<span style="color:#f92672">*</span><span style="color:#ae81ff">4</span>))  
</code></pre></div><h2 id="exploratory-data-analysis-eda">Exploratory Data Analysis (EDA)</h2>
<h3 id="general-overview">General Overview</h3>
<p>Using <code>skim()</code> and <code>glimpse()</code>, we can have a general overview of the data. The dataset used in our analysis, <code>listings_selected</code> contains 23 variables and 7,186 obvervations. <code>id</code> is the unique key of the dataset. Besides, we have 14 numeric variables. <code>prop_type_simplified</code>, <code>room_type</code>, and <code>cancellation_policy</code> are factor variables.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">glimpse</span>(listings_selected)
</code></pre></div><pre><code>## Rows: 7,186
## Columns: 23
## $ id                     &lt;dbl&gt; 2352, 2354, 45145, 48180, 71744, 80257, 80320,…
## $ price                  &lt;dbl&gt; 93, 78, 100, 200, 60, 95, 85, 85, 135, 70, 85,…
## $ cleaning_fee           &lt;dbl&gt; 65, 65, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 60, 0, …
## $ extra_people           &lt;dbl&gt; 5, 0, 30, 20, 15, 20, 10, 10, 25, 20, 10, 45, …
## $ prop_type_simplified   &lt;chr&gt; &quot;Apartment&quot;, &quot;Apartment&quot;, &quot;Other&quot;, &quot;Apartment&quot;…
## $ room_type              &lt;chr&gt; &quot;Entire home/apt&quot;, &quot;Entire home/apt&quot;, &quot;Hotel r…
## $ minimum_nights         &lt;dbl&gt; 2, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 1…
## $ guests_included        &lt;dbl&gt; 4, 1, 1, 1, 2, 2, 2, 2, 4, 2, 2, 1, 1, 2, 2, 2…
## $ number_of_reviews      &lt;dbl&gt; 15, 2, 3, 0, 12, 4, 59, 6, 48, 25, 33, 3, 1, 4…
## $ review_scores_rating   &lt;dbl&gt; 87.0, 80.0, 100.0, 92.7, 98.0, 90.0, 93.0, 97.…
## $ longitude              &lt;dbl&gt; 4.31, 4.31, 4.37, 4.41, 4.35, 4.34, 4.34, 4.34…
## $ latitude               &lt;dbl&gt; 50.9, 50.9, 50.9, 50.8, 50.9, 50.8, 50.8, 50.8…
## $ neighbourhood          &lt;chr&gt; &quot;Molenbeek-Saint-Jean&quot;, &quot;Molenbeek-Saint-Jean&quot;…
## $ neighbourhood_cleansed &lt;chr&gt; &quot;Molenbeek-Saint-Jean&quot;, &quot;Molenbeek-Saint-Jean&quot;…
## $ listing_url            &lt;chr&gt; &quot;https://www.airbnb.com/rooms/2352&quot;, &quot;https://…
## $ bathrooms              &lt;dbl&gt; 1.0, 1.0, 1.0, 1.5, 1.0, 1.0, 1.0, 1.0, 2.0, 1…
## $ bedrooms               &lt;dbl&gt; 2, 1, 1, 2, 1, 0, 0, 0, 1, 0, 1, 2, 1, 0, 1, 0…
## $ beds                   &lt;dbl&gt; 2, 1, 1, 2, 1, 2, 2, 2, 4, 2, 3, 3, 1, 2, 1, 2…
## $ accommodates           &lt;dbl&gt; 5, 4, 2, 2, 2, 3, 3, 3, 6, 3, 4, 4, 2, 3, 2, 3…
## $ host_is_superhost      &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALS…
## $ is_location_exact      &lt;lgl&gt; TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRU…
## $ cancellation_policy    &lt;chr&gt; &quot;strict_14_with_grace_period&quot;, &quot;strict_14_with…
## $ price_4_nights         &lt;dbl&gt; 632, 572, 520, 880, 300, 380, 340, 340, 540, 2…
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">skim</span>(listings_selected)
</code></pre></div><p>Table: Data summary</p>
<table>
<thead>
<tr>
<th style="text-align:left"></th>
<th style="text-align:left"></th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">Name</td>
<td style="text-align:left">listings_selected</td>
</tr>
<tr>
<td style="text-align:left">Number of rows</td>
<td style="text-align:left">7186</td>
</tr>
<tr>
<td style="text-align:left">Number of columns</td>
<td style="text-align:left">23</td>
</tr>
<tr>
<td style="text-align:left">_______________________</td>
<td style="text-align:left"></td>
</tr>
<tr>
<td style="text-align:left">Column type frequency:</td>
<td style="text-align:left"></td>
</tr>
<tr>
<td style="text-align:left">character</td>
<td style="text-align:left">6</td>
</tr>
<tr>
<td style="text-align:left">logical</td>
<td style="text-align:left">2</td>
</tr>
<tr>
<td style="text-align:left">numeric</td>
<td style="text-align:left">15</td>
</tr>
<tr>
<td style="text-align:left">________________________</td>
<td style="text-align:left"></td>
</tr>
<tr>
<td style="text-align:left">Group variables</td>
<td style="text-align:left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left">skim_variable</th>
<th style="text-align:right">n_missing</th>
<th style="text-align:right">complete_rate</th>
<th style="text-align:right">min</th>
<th style="text-align:right">max</th>
<th style="text-align:right">empty</th>
<th style="text-align:right">n_unique</th>
<th style="text-align:right">whitespace</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">prop_type_simplified</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">5</td>
<td style="text-align:right">11</td>
<td style="text-align:right">0</td>
<td style="text-align:right">5</td>
<td style="text-align:right">0</td>
</tr>
<tr>
<td style="text-align:left">room_type</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">10</td>
<td style="text-align:right">15</td>
<td style="text-align:right">0</td>
<td style="text-align:right">4</td>
<td style="text-align:right">0</td>
</tr>
<tr>
<td style="text-align:left">neighbourhood</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">5</td>
<td style="text-align:right">21</td>
<td style="text-align:right">0</td>
<td style="text-align:right">49</td>
<td style="text-align:right">0</td>
</tr>
<tr>
<td style="text-align:left">neighbourhood_cleansed</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">5</td>
<td style="text-align:right">21</td>
<td style="text-align:right">0</td>
<td style="text-align:right">19</td>
<td style="text-align:right">0</td>
</tr>
<tr>
<td style="text-align:left">listing_url</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">33</td>
<td style="text-align:right">37</td>
<td style="text-align:right">0</td>
<td style="text-align:right">7186</td>
<td style="text-align:right">0</td>
</tr>
<tr>
<td style="text-align:left">cancellation_policy</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">8</td>
<td style="text-align:right">27</td>
<td style="text-align:right">0</td>
<td style="text-align:right">5</td>
<td style="text-align:right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: logical</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left">skim_variable</th>
<th style="text-align:right">n_missing</th>
<th style="text-align:right">complete_rate</th>
<th style="text-align:right">mean</th>
<th style="text-align:left">count</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">host_is_superhost</td>
<td style="text-align:right">3</td>
<td style="text-align:right">1</td>
<td style="text-align:right">0.18</td>
<td style="text-align:left">FAL: 5870, TRU: 1313</td>
</tr>
<tr>
<td style="text-align:left">is_location_exact</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">0.84</td>
<td style="text-align:left">TRU: 6006, FAL: 1180</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left">skim_variable</th>
<th style="text-align:right">n_missing</th>
<th style="text-align:right">complete_rate</th>
<th style="text-align:right">mean</th>
<th style="text-align:right">sd</th>
<th style="text-align:right">p0</th>
<th style="text-align:right">p25</th>
<th style="text-align:right">p50</th>
<th style="text-align:right">p75</th>
<th style="text-align:right">p100</th>
<th style="text-align:left">hist</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">id</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">2.48e+07</td>
<td style="text-align:right">1.28e+07</td>
<td style="text-align:right">2352.00</td>
<td style="text-align:right">1.38e+07</td>
<td style="text-align:right">2.58e+07</td>
<td style="text-align:right">3.68e+07</td>
<td style="text-align:right">4.38e+07</td>
<td style="text-align:left">▅▅▅▅▇</td>
</tr>
<tr>
<td style="text-align:left">price</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">7.86e+01</td>
<td style="text-align:right">1.17e+02</td>
<td style="text-align:right">0.00</td>
<td style="text-align:right">4.20e+01</td>
<td style="text-align:right">6.00e+01</td>
<td style="text-align:right">8.90e+01</td>
<td style="text-align:right">7.00e+03</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
<tr>
<td style="text-align:left">cleaning_fee</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">1.90e+01</td>
<td style="text-align:right">2.37e+01</td>
<td style="text-align:right">0.00</td>
<td style="text-align:right">0.00e+00</td>
<td style="text-align:right">1.20e+01</td>
<td style="text-align:right">3.00e+01</td>
<td style="text-align:right">5.05e+02</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
<tr>
<td style="text-align:left">extra_people</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">7.86e+00</td>
<td style="text-align:right">1.24e+01</td>
<td style="text-align:right">0.00</td>
<td style="text-align:right">0.00e+00</td>
<td style="text-align:right">0.00e+00</td>
<td style="text-align:right">1.50e+01</td>
<td style="text-align:right">2.69e+02</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
<tr>
<td style="text-align:left">minimum_nights</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">1.88e+00</td>
<td style="text-align:right">8.90e-01</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">2.00e+00</td>
<td style="text-align:right">2.00e+00</td>
<td style="text-align:right">4.00e+00</td>
<td style="text-align:left">▇▇▁▃▁</td>
</tr>
<tr>
<td style="text-align:left">guests_included</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">1.53e+00</td>
<td style="text-align:right">1.06e+00</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">2.00e+00</td>
<td style="text-align:right">1.60e+01</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
<tr>
<td style="text-align:left">number_of_reviews</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">3.49e+01</td>
<td style="text-align:right">6.65e+01</td>
<td style="text-align:right">0.00</td>
<td style="text-align:right">2.00e+00</td>
<td style="text-align:right">9.00e+00</td>
<td style="text-align:right">3.50e+01</td>
<td style="text-align:right">7.66e+02</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
<tr>
<td style="text-align:left">review_scores_rating</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">9.27e+01</td>
<td style="text-align:right">7.77e+00</td>
<td style="text-align:right">20.00</td>
<td style="text-align:right">9.10e+01</td>
<td style="text-align:right">9.30e+01</td>
<td style="text-align:right">9.80e+01</td>
<td style="text-align:right">1.00e+02</td>
<td style="text-align:left">▁▁▁▁▇</td>
</tr>
<tr>
<td style="text-align:left">longitude</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">4.36e+00</td>
<td style="text-align:right">3.00e-02</td>
<td style="text-align:right">4.26</td>
<td style="text-align:right">4.34e+00</td>
<td style="text-align:right">4.36e+00</td>
<td style="text-align:right">4.38e+00</td>
<td style="text-align:right">4.49e+00</td>
<td style="text-align:left">▁▆▇▂▁</td>
</tr>
<tr>
<td style="text-align:left">latitude</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">5.08e+01</td>
<td style="text-align:right">2.00e-02</td>
<td style="text-align:right">50.77</td>
<td style="text-align:right">5.08e+01</td>
<td style="text-align:right">5.08e+01</td>
<td style="text-align:right">5.09e+01</td>
<td style="text-align:right">5.09e+01</td>
<td style="text-align:left">▁▂▇▃▁</td>
</tr>
<tr>
<td style="text-align:left">bathrooms</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">1.18e+00</td>
<td style="text-align:right">5.90e-01</td>
<td style="text-align:right">0.00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">3.00e+01</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
<tr>
<td style="text-align:left">bedrooms</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">1.22e+00</td>
<td style="text-align:right">8.50e-01</td>
<td style="text-align:right">0.00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">3.00e+01</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
<tr>
<td style="text-align:left">beds</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">1.74e+00</td>
<td style="text-align:right">1.32e+00</td>
<td style="text-align:right">0.00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">1.00e+00</td>
<td style="text-align:right">2.00e+00</td>
<td style="text-align:right">3.10e+01</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
<tr>
<td style="text-align:left">accommodates</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">3.08e+00</td>
<td style="text-align:right">1.77e+00</td>
<td style="text-align:right">1.00</td>
<td style="text-align:right">2.00e+00</td>
<td style="text-align:right">2.00e+00</td>
<td style="text-align:right">4.00e+00</td>
<td style="text-align:right">1.60e+01</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
<tr>
<td style="text-align:left">price_4_nights</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">4.01e+02</td>
<td style="text-align:right">4.95e+02</td>
<td style="text-align:right">36.00</td>
<td style="text-align:right">2.20e+02</td>
<td style="text-align:right">3.20e+02</td>
<td style="text-align:right">4.60e+02</td>
<td style="text-align:right">2.80e+04</td>
<td style="text-align:left">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
<h3 id="distribution-of-price">Distribution of Price</h3>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e"># A general overview</span>
mosaic<span style="color:#f92672">::</span><span style="color:#a6e22e">favstats</span>(listings_selected<span style="color:#f92672">$</span>price_4_nights)
</code></pre></div><p>preserve68f4128db5122596</p>
<p>We take logrithm of <code>price_4_nights</code> and create the density plot. As we can see, the logrithm of price is more like a normal distribution. In our analysis, we will use log(price) as the variable Y to explain.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e"># Create the density plot</span>
<span style="color:#a6e22e">ggplot</span>(listings_selected,<span style="color:#a6e22e">aes</span>(x<span style="color:#f92672">=</span>price_4_nights))<span style="color:#f92672">+</span>
  <span style="color:#a6e22e">geom_density</span>(<span style="color:#a6e22e">aes</span>(x<span style="color:#f92672">=</span>price_4_nights))<span style="color:#f92672">+</span>
  <span style="color:#a6e22e">scale_x_log10</span>()<span style="color:#f92672">+</span>
  <span style="color:#a6e22e">labs</span>(title<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;Density plot of 4-night Airbnb prices&#34;</span>,
       x<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;Price [$]&#34;</span>,
       y<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;Density&#34;</span>)<span style="color:#f92672">+</span>
  <span style="color:#a6e22e">theme_minimal</span>()
</code></pre></div><p><!-- raw HTML omitted --></p>
<h3 id="review-scores-rating">Review Scores Rating</h3>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e"># A general overview</span>
mosaic<span style="color:#f92672">::</span><span style="color:#a6e22e">favstats</span>(listings_selected<span style="color:#f92672">$</span>review_scores_rating)
</code></pre></div><p>preserve590fe587cdd475bc</p>
<p>We are also interested whether there&rsquo;s relationship between number of reviews and review scores rating. We divide number of reviews into 4 quartiles and create the boxplot of <code>review_scores_rating</code> for each quartile.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e"># Divide `number_of_reviews` into 4 quartiles</span>
review_groups <span style="color:#f92672">&lt;-</span> listings_selected <span style="color:#f92672">%&gt;%</span> 
  <span style="color:#a6e22e">mutate</span>(consolidated_ratings_numbers <span style="color:#f92672">=</span> <span style="color:#a6e22e">ntile</span>( number_of_reviews, <span style="color:#ae81ff">4</span> ))

<span style="color:#75715e"># Convert into factor</span>
review_groups<span style="color:#f92672">$</span>consolidated_ratings_numbers <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">as.factor</span>(review_groups<span style="color:#f92672">$</span>consolidated_ratings_numbers)  

<span style="color:#75715e"># Create the boxplot of `review_scores_rating` for each quartile</span>
<span style="color:#a6e22e">ggplot</span>(review_groups, <span style="color:#a6e22e">aes</span>(x <span style="color:#f92672">=</span> consolidated_ratings_numbers, y <span style="color:#f92672">=</span> review_scores_rating)) <span style="color:#f92672">+</span>
  <span style="color:#a6e22e">geom_boxplot</span>()<span style="color:#f92672">+</span>
  <span style="color:#a6e22e">labs</span>(title<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;Distributing of review scores rating within different number-of-review quartiles&#34;</span>,
       x<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;Quartile of number of reviews&#34;</span>,
       y<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;Review scores rating&#34;</span>)<span style="color:#f92672">+</span>
  <span style="color:#a6e22e">theme_minimal</span>(base_size<span style="color:#f92672">=</span><span style="color:#ae81ff">9</span>)
</code></pre></div><p><!-- raw HTML omitted --></p>
<p>As we can see from the chart above. In the first quartile of reviews, the deviation of review scores rating from the mean is the lowest. This suggest with more review, opinions become more unified.</p>
<h3 id="correlation-between-price-and-scores-rating">Correlation Between Price and Scores Rating</h3>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">listings_selected <span style="color:#f92672">%&gt;%</span>
  <span style="color:#a6e22e">ggplot</span>(<span style="color:#a6e22e">aes</span>(x<span style="color:#f92672">=</span>review_scores_rating,y<span style="color:#f92672">=</span>price_4_nights))<span style="color:#f92672">+</span>
  <span style="color:#a6e22e">geom_point</span>()<span style="color:#f92672">+</span>
  <span style="color:#a6e22e">scale_y_log10</span>()<span style="color:#f92672">+</span>
  <span style="color:#a6e22e">geom_smooth</span>()<span style="color:#f92672">+</span>
  <span style="color:#a6e22e">labs</span>(title<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;Relationship between price and scores rating&#34;</span>,
       x<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;Scores rating&#34;</span>,
       y<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;Price&#34;</span>)<span style="color:#f92672">+</span>
  <span style="color:#a6e22e">theme_minimal</span>()
</code></pre></div><p><!-- raw HTML omitted --></p>
<p>As we can see, there&rsquo;s no clear relationship between price and scores rating.</p>
<h3 id="correlation-between-price-and-size-of-house">Correlation Between Price and Size of House</h3>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">ggplot</span>(listings_selected,<span style="color:#a6e22e">aes</span>(x<span style="color:#f92672">=</span>accommodates,y<span style="color:#f92672">=</span>price_4_nights))<span style="color:#f92672">+</span>
  <span style="color:#a6e22e">geom_point</span>()<span style="color:#f92672">+</span>
  <span style="color:#a6e22e">geom_smooth</span>()<span style="color:#f92672">+</span>
  <span style="color:#a6e22e">scale_y_log10</span>()<span style="color:#f92672">+</span>
  <span style="color:#a6e22e">labs</span>(title<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;Relationship between price and size of house&#34;</span>,
       x<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;Size of house&#34;</span>,
       y<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;Price&#34;</span>)<span style="color:#f92672">+</span>
  <span style="color:#a6e22e">theme_minimal</span>()
</code></pre></div><p><!-- raw HTML omitted --></p>
<p>It seems that the larger the house, the higher the cost.</p>
<h1 id="regression-analysis">Regression Analysis</h1>
<p>In this section, we are going to present our regression analysis. For the target variable Y, we will use the logrithm of the cost for two people to stay at an Airbnb location for four nights.</p>
<h2 id="model-1">Model 1</h2>
<p>Model 1 uses following explanatory variables: <code>prop_type_simplified</code>, <code>number_of_reviews</code>, and <code>review_scores_rating</code>. Since <code>number_of_reviews</code> is also potentially unbounded and obviously skews right, we also take the logrithm for it.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">listings_selected<span style="color:#f92672">&lt;-</span>listings_selected <span style="color:#f92672">%&gt;%</span>
  <span style="color:#a6e22e">mutate</span>(log_numberofreview<span style="color:#f92672">=</span><span style="color:#a6e22e">log</span>(<span style="color:#ae81ff">1</span><span style="color:#f92672">+</span>number_of_reviews))
</code></pre></div><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">model1 <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">lm</span>(<span style="color:#a6e22e">log</span>(price_4_nights) <span style="color:#f92672">~</span> prop_type_simplified<span style="color:#f92672">+</span>log_numberofreview<span style="color:#f92672">+</span>review_scores_rating,
             data<span style="color:#f92672">=</span>listings_selected)

<span style="color:#a6e22e">summary</span>(model1)
</code></pre></div><pre><code>## 
## Call:
## lm(formula = log(price_4_nights) ~ prop_type_simplified + log_numberofreview + 
##     review_scores_rating, data = listings_selected)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -2.181 -0.395 -0.013  0.346  4.172 
## 
## Coefficients:
##                                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                      5.444816   0.084899   64.13  &lt; 2e-16 ***
## prop_type_simplifiedCondominium  0.078874   0.035023    2.25  0.02435 *  
## prop_type_simplifiedHouse       -0.099920   0.024816   -4.03  5.7e-05 ***
## prop_type_simplifiedOther        0.335774   0.022942   14.64  &lt; 2e-16 ***
## prop_type_simplifiedTownhouse   -0.121011   0.035875   -3.37  0.00075 ***
## log_numberofreview               0.008575   0.004398    1.95  0.05126 .  
## review_scores_rating             0.003104   0.000909    3.41  0.00064 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.597 on 7179 degrees of freedom
## Multiple R-squared:  0.038,	Adjusted R-squared:  0.0372 
## F-statistic: 47.2 on 6 and 7179 DF,  p-value: &lt;2e-16
</code></pre><blockquote>
<p>Intepret the coefficient of <code>review_scores_rating</code> in terms of <code>price_4_nights</code></p>
</blockquote>
<p>For the review score rating, the Estimate is 3.110e-03, with a p-value of 0.000359. Hence this is statistically significant and every 10 review score units higher will lead to a relative increase of 3.11% in price for a 4-day stay.</p>
<blockquote>
<p>Intepret the coefficient of <code>pop_type_simplified</code> in terms of <code>price_4_nights</code></p>
</blockquote>
<p>For the property types, the Estimate the following p-values are given (while taking apartment as the intercept): 0.03383 for Condominiums (still considered statistically relevant), 2.45e-06 for Houses (considered statistically relevant), &lt;2.46e-06 for Other (statistically relevant) and 5.27e-06 for Townshouse (also statistically relevant). Hence, all housing types included in the simplified list will have a statically significant effect, ranging from 7.595% to 28.74% in increase/decrease.</p>
<h2 id="model-2">Model 2</h2>
<p>Secondly, we want to determine if <code>room_type</code> is a significant predictor of the cost for 4 nights, given everything else in the model. We thus fit a regression model called <code>model2</code> that includes all of the explanatory variabes in <code>model1</code> plus <code>room_type</code>.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e"># Added &#34;room_type&#34; to list </span>
model2 <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">lm</span>(<span style="color:#a6e22e">log</span>(price_4_nights) <span style="color:#f92672">~</span> prop_type_simplified <span style="color:#f92672">+</span> log_numberofreview <span style="color:#f92672">+</span> review_scores_rating <span style="color:#f92672">+</span> room_type, data <span style="color:#f92672">=</span> listings_selected)

<span style="color:#a6e22e">summary</span>(model2)
</code></pre></div><pre><code>## 
## Call:
## lm(formula = log(price_4_nights) ~ prop_type_simplified + log_numberofreview + 
##     review_scores_rating + room_type, data = listings_selected)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -2.261 -0.326 -0.022  0.271  4.583 
## 
## Coefficients:
##                                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                      5.606347   0.072503   77.33  &lt; 2e-16 ***
## prop_type_simplifiedCondominium  0.077207   0.029884    2.58   0.0098 ** 
## prop_type_simplifiedHouse        0.181202   0.021886    8.28  &lt; 2e-16 ***
## prop_type_simplifiedOther        0.391418   0.020706   18.90  &lt; 2e-16 ***
## prop_type_simplifiedTownhouse    0.207775   0.031301    6.64  3.4e-11 ***
## log_numberofreview              -0.002869   0.003768   -0.76   0.4465    
## review_scores_rating             0.003698   0.000776    4.77  1.9e-06 ***
## room_typeHotel room              0.035925   0.058035    0.62   0.5359    
## room_typePrivate room           -0.683811   0.013564  -50.41  &lt; 2e-16 ***
## room_typeShared room            -0.903252   0.061897  -14.59  &lt; 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.51 on 7176 degrees of freedom
## Multiple R-squared:   0.3,	Adjusted R-squared:  0.299 
## F-statistic:  342 on 9 and 7176 DF,  p-value: &lt;2e-16
</code></pre><p>Hotel rooms are not considered statistically relevant (i.e.p = 0.4688 &raquo; 0.05). However, Private rooms and Shared rooms are considered statistically relevant (both with p &lt; 2e-16 &laquo; 0.05). Consequently, we should account for a 69.22% and 92.73% decrease for shared rooms.</p>
<h2 id="model-3">Model 3</h2>
<p>Thirdly, we add <code>bathrooms</code>, <code>bedrooms</code>, <code>beds</code> and size of the house <code>accommodates</code> to the model to see whether they are significant predictors of <code>price_4_nights</code>.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">model3a <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">lm</span>(<span style="color:#a6e22e">log</span>(price_4_nights) <span style="color:#f92672">~</span> bathrooms <span style="color:#f92672">+</span> bedrooms <span style="color:#f92672">+</span> beds <span style="color:#f92672">+</span> accommodates, data <span style="color:#f92672">=</span> listings_selected)

model3b <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">lm</span>(<span style="color:#a6e22e">log</span>(price_4_nights) <span style="color:#f92672">~</span> prop_type_simplified <span style="color:#f92672">+</span> log_numberofreview <span style="color:#f92672">+</span> review_scores_rating <span style="color:#f92672">+</span> room_type <span style="color:#f92672">+</span> bathrooms <span style="color:#f92672">+</span> bedrooms <span style="color:#f92672">+</span> beds <span style="color:#f92672">+</span> accommodates, data <span style="color:#f92672">=</span> listings_selected)

<span style="color:#a6e22e">summary</span>(model3a)
</code></pre></div><pre><code>## 
## Call:
## lm(formula = log(price_4_nights) ~ bathrooms + bedrooms + beds + 
##     accommodates, data = listings_selected)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -2.239 -0.299  0.004  0.287  4.312 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   5.20469    0.01510  344.59  &lt; 2e-16 ***
## bathrooms    -0.04636    0.01246   -3.72  0.00020 ***
## bedrooms      0.04153    0.01091    3.81  0.00014 ***
## beds         -0.02984    0.00779   -3.83  0.00013 ***
## accommodates  0.20441    0.00560   36.52  &lt; 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.502 on 7181 degrees of freedom
## Multiple R-squared:  0.321,	Adjusted R-squared:  0.32 
## F-statistic:  848 on 4 and 7181 DF,  p-value: &lt;2e-16
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">summary</span>(model3b)
</code></pre></div><pre><code>## 
## Call:
## lm(formula = log(price_4_nights) ~ prop_type_simplified + log_numberofreview + 
##     review_scores_rating + room_type + bathrooms + bedrooms + 
##     beds + accommodates, data = listings_selected)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -2.979 -0.278 -0.015  0.250  4.408 
## 
## Coefficients:
##                                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                      4.981571   0.066394   75.03  &lt; 2e-16 ***
## prop_type_simplifiedCondominium  0.082221   0.026519    3.10   0.0019 ** 
## prop_type_simplifiedHouse        0.026787   0.019841    1.35   0.1770    
## prop_type_simplifiedOther        0.289029   0.018543   15.59  &lt; 2e-16 ***
## prop_type_simplifiedTownhouse    0.071114   0.028026    2.54   0.0112 *  
## log_numberofreview              -0.008331   0.003369   -2.47   0.0134 *  
## review_scores_rating             0.005096   0.000691    7.38  1.8e-13 ***
## room_typeHotel room              0.241896   0.051740    4.68  3.0e-06 ***
## room_typePrivate room           -0.446790   0.013408  -33.32  &lt; 2e-16 ***
## room_typeShared room            -0.654179   0.055354  -11.82  &lt; 2e-16 ***
## bathrooms                       -0.015521   0.011296   -1.37   0.1695    
## bedrooms                         0.072983   0.009955    7.33  2.5e-13 ***
## beds                            -0.028523   0.007067   -4.04  5.5e-05 ***
## accommodates                     0.140923   0.005398   26.11  &lt; 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.452 on 7172 degrees of freedom
## Multiple R-squared:  0.45,	Adjusted R-squared:  0.449 
## F-statistic:  451 on 13 and 7172 DF,  p-value: &lt;2e-16
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e"># Check for colinearity</span>
<span style="color:#a6e22e">vif</span>(model3b)
</code></pre></div><pre><code>##                      GVIF Df GVIF^(1/(2*Df))
## prop_type_simplified 1.34  4            1.04
## log_numberofreview   1.03  1            1.02
## review_scores_rating 1.01  1            1.01
## room_type            1.57  3            1.08
## bathrooms            1.54  1            1.24
## bedrooms             2.55  1            1.60
## beds                 3.07  1            1.75
## accommodates         3.19  1            1.79
</code></pre><p>When running a regression model for bedrooms, beds and bathrooms (separately and included in our prior model) we see that the p-values are all less than 1%. Hence, all 3 of these variables are to be considered as statically significant.</p>
<h2 id="model-4">Model 4</h2>
<p>We are also curious whether <code>host_is_superhost</code> command a pricing premium, after controlling for other variables.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">model4a <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">lm</span>(<span style="color:#a6e22e">log</span>(price_4_nights) <span style="color:#f92672">~</span> host_is_superhost, data <span style="color:#f92672">=</span> listings_selected)

<span style="color:#a6e22e">summary</span>(model4a)
</code></pre></div><pre><code>## 
## Call:
## lm(formula = log(price_4_nights) ~ host_is_superhost, data = listings_selected)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -2.174 -0.401 -0.001  0.339  4.483 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)            5.75720    0.00792  726.56  &lt; 2e-16 ***
## host_is_superhostTRUE  0.11907    0.01853    6.42  1.4e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.607 on 7181 degrees of freedom
##   (3 observations deleted due to missingness)
## Multiple R-squared:  0.00571,	Adjusted R-squared:  0.00558 
## F-statistic: 41.3 on 1 and 7181 DF,  p-value: 1.41e-10
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">model4b <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">lm</span>(<span style="color:#a6e22e">log</span>(price_4_nights) <span style="color:#f92672">~</span>prop_type_simplified <span style="color:#f92672">+</span> log_numberofreview <span style="color:#f92672">+</span> review_scores_rating <span style="color:#f92672">+</span> room_type <span style="color:#f92672">+</span> bathrooms <span style="color:#f92672">+</span> bedrooms <span style="color:#f92672">+</span> beds <span style="color:#f92672">+</span> host_is_superhost, data <span style="color:#f92672">=</span> listings_selected)

<span style="color:#a6e22e">summary</span>(model4b)
</code></pre></div><pre><code>## 
## Call:
## lm(formula = log(price_4_nights) ~ prop_type_simplified + log_numberofreview + 
##     review_scores_rating + room_type + bathrooms + bedrooms + 
##     beds + host_is_superhost, data = listings_selected)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -5.902 -0.290 -0.015  0.248  4.467 
## 
## Coefficients:
##                                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                      5.425934   0.070174   77.32  &lt; 2e-16 ***
## prop_type_simplifiedCondominium  0.069138   0.027597    2.51   0.0123 *  
## prop_type_simplifiedHouse        0.037375   0.020641    1.81   0.0702 .  
## prop_type_simplifiedOther        0.323013   0.019256   16.78  &lt; 2e-16 ***
## prop_type_simplifiedTownhouse    0.073619   0.029199    2.52   0.0117 *  
## log_numberofreview              -0.015201   0.003713   -4.09  4.3e-05 ***
## review_scores_rating             0.002512   0.000741    3.39   0.0007 ***
## room_typeHotel room              0.106902   0.053693    1.99   0.0465 *  
## room_typePrivate room           -0.561589   0.013197  -42.56  &lt; 2e-16 ***
## room_typeShared room            -0.821199   0.057195  -14.36  &lt; 2e-16 ***
## bathrooms                       -0.031428   0.011748   -2.68   0.0075 ** 
## bedrooms                         0.145944   0.009931   14.70  &lt; 2e-16 ***
## beds                             0.079278   0.006050   13.10  &lt; 2e-16 ***
## host_is_superhostTRUE            0.141487   0.015772    8.97  &lt; 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.47 on 7169 degrees of freedom
##   (3 observations deleted due to missingness)
## Multiple R-squared:  0.404,	Adjusted R-squared:  0.403 
## F-statistic:  374 on 13 and 7169 DF,  p-value: &lt;2e-16
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e"># Check for colinearity</span>
<span style="color:#a6e22e">vif</span>(model4b)
</code></pre></div><pre><code>##                      GVIF Df GVIF^(1/(2*Df))
## prop_type_simplified 1.33  4            1.04
## log_numberofreview   1.16  1            1.08
## review_scores_rating 1.07  1            1.04
## room_type            1.39  3            1.06
## bathrooms            1.54  1            1.24
## bedrooms             2.34  1            1.53
## beds                 2.08  1            1.44
## host_is_superhost    1.21  1            1.10
</code></pre><p>When running a regression model for host_is_superhost (separately and included in our prior model) we see that the p-value of this variable is negligible. Hence, host_is_superhost  is to be considered as statically significant.</p>
<h2 id="model-5">Model 5</h2>
<p>Most owners advertise the exact location of their listing (<code>is_location_exact==TRUE</code>), while a non-trivial proportion don&rsquo;t. We are going to find out, after controlling for other variables, is a listing&rsquo;s exact location a significant predictor of <code>price_4_nights</code>.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">model5a <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">lm</span>(<span style="color:#a6e22e">log</span>(price_4_nights) <span style="color:#f92672">~</span> is_location_exact, data <span style="color:#f92672">=</span> listings_selected)

<span style="color:#a6e22e">summary</span>(model5a)
</code></pre></div><pre><code>## 
## Call:
## lm(formula = log(price_4_nights) ~ is_location_exact, data = listings_selected)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -2.208 -0.398 -0.023  0.361  4.449 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)             5.7150     0.0177  322.85  &lt; 2e-16 ***
## is_location_exactTRUE   0.0764     0.0194    3.94  8.1e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.608 on 7184 degrees of freedom
## Multiple R-squared:  0.00216,	Adjusted R-squared:  0.00202 
## F-statistic: 15.6 on 1 and 7184 DF,  p-value: 8.09e-05
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">model5b <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">lm</span>(<span style="color:#a6e22e">log</span>(price_4_nights) <span style="color:#f92672">~</span>prop_type_simplified <span style="color:#f92672">+</span> log_numberofreview <span style="color:#f92672">+</span> review_scores_rating <span style="color:#f92672">+</span> is_location_exact, data <span style="color:#f92672">=</span> listings_selected)

<span style="color:#a6e22e">summary</span>(model5b)
</code></pre></div><pre><code>## 
## Call:
## lm(formula = log(price_4_nights) ~ prop_type_simplified + log_numberofreview + 
##     review_scores_rating + is_location_exact, data = listings_selected)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -2.193 -0.393 -0.015  0.344  4.155 
## 
## Coefficients:
##                                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                      5.389829   0.085910   62.74  &lt; 2e-16 ***
## prop_type_simplifiedCondominium  0.082642   0.034999    2.36  0.01824 *  
## prop_type_simplifiedHouse       -0.101743   0.024794   -4.10  4.1e-05 ***
## prop_type_simplifiedOther        0.335868   0.022918   14.66  &lt; 2e-16 ***
## prop_type_simplifiedTownhouse   -0.123372   0.035842   -3.44  0.00058 ***
## log_numberofreview               0.007149   0.004408    1.62  0.10490    
## review_scores_rating             0.003045   0.000908    3.35  0.00081 ***
## is_location_exactTRUE            0.076515   0.019075    4.01  6.1e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.597 on 7178 degrees of freedom
## Multiple R-squared:  0.0401,	Adjusted R-squared:  0.0392 
## F-statistic: 42.9 on 7 and 7178 DF,  p-value: &lt;2e-16
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">model5c <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">lm</span>(<span style="color:#a6e22e">log</span>(price_4_nights) <span style="color:#f92672">~</span>prop_type_simplified <span style="color:#f92672">+</span> log_numberofreview <span style="color:#f92672">+</span> review_scores_rating <span style="color:#f92672">+</span> room_type <span style="color:#f92672">+</span> is_location_exact, data <span style="color:#f92672">=</span> listings_selected)

<span style="color:#a6e22e">summary</span>(model5c)
</code></pre></div><pre><code>## 
## Call:
## lm(formula = log(price_4_nights) ~ prop_type_simplified + log_numberofreview + 
##     review_scores_rating + room_type + is_location_exact, data = listings_selected)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -2.267 -0.330 -0.021  0.273  4.574 
## 
## Coefficients:
##                                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                      5.576300   0.073441   75.93  &lt; 2e-16 ***
## prop_type_simplifiedCondominium  0.079279   0.029884    2.65    0.008 ** 
## prop_type_simplifiedHouse        0.179709   0.021885    8.21  2.6e-16 ***
## prop_type_simplifiedOther        0.391292   0.020698   18.90  &lt; 2e-16 ***
## prop_type_simplifiedTownhouse    0.205923   0.031297    6.58  5.1e-11 ***
## log_numberofreview              -0.003605   0.003778   -0.95    0.340    
## review_scores_rating             0.003665   0.000776    4.73  2.3e-06 ***
## room_typeHotel room              0.036520   0.058014    0.63    0.529    
## room_typePrivate room           -0.682584   0.013567  -50.31  &lt; 2e-16 ***
## room_typeShared room            -0.897406   0.061917  -14.49  &lt; 2e-16 ***
## is_location_exactTRUE            0.041271   0.016304    2.53    0.011 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.509 on 7175 degrees of freedom
## Multiple R-squared:  0.301,	Adjusted R-squared:   0.3 
## F-statistic:  309 on 10 and 7175 DF,  p-value: &lt;2e-16
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">model5d <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">lm</span>(<span style="color:#a6e22e">log</span>(price_4_nights) <span style="color:#f92672">~</span>prop_type_simplified <span style="color:#f92672">+</span> log_numberofreview <span style="color:#f92672">+</span> review_scores_rating <span style="color:#f92672">+</span> room_type <span style="color:#f92672">+</span> bathrooms <span style="color:#f92672">+</span> bedrooms <span style="color:#f92672">+</span> beds <span style="color:#f92672">+</span> host_is_superhost <span style="color:#f92672">+</span> is_location_exact, data <span style="color:#f92672">=</span> listings_selected)

<span style="color:#a6e22e">summary</span>(model5d)
</code></pre></div><pre><code>## 
## Call:
## lm(formula = log(price_4_nights) ~ prop_type_simplified + log_numberofreview + 
##     review_scores_rating + room_type + bathrooms + bedrooms + 
##     beds + host_is_superhost + is_location_exact, data = listings_selected)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -5.897 -0.291 -0.015  0.250  4.460 
## 
## Coefficients:
##                                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                      5.40305    0.07101   76.08  &lt; 2e-16 ***
## prop_type_simplifiedCondominium  0.07075    0.02760    2.56  0.01039 *  
## prop_type_simplifiedHouse        0.03640    0.02064    1.76  0.07786 .  
## prop_type_simplifiedOther        0.32299    0.01925   16.78  &lt; 2e-16 ***
## prop_type_simplifiedTownhouse    0.07244    0.02920    2.48  0.01312 *  
## log_numberofreview              -0.01571    0.00372   -4.22  2.4e-05 ***
## review_scores_rating             0.00249    0.00074    3.37  0.00076 ***
## room_typeHotel room              0.10737    0.05368    2.00  0.04551 *  
## room_typePrivate room           -0.56073    0.01320  -42.48  &lt; 2e-16 ***
## room_typeShared room            -0.81682    0.05722  -14.27  &lt; 2e-16 ***
## bathrooms                       -0.03185    0.01175   -2.71  0.00671 ** 
## bedrooms                         0.14606    0.00993   14.71  &lt; 2e-16 ***
## beds                             0.07916    0.00605   13.09  &lt; 2e-16 ***
## host_is_superhostTRUE            0.14087    0.01577    8.93  &lt; 2e-16 ***
## is_location_exactTRUE            0.03135    0.01507    2.08  0.03748 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.47 on 7168 degrees of freedom
##   (3 observations deleted due to missingness)
## Multiple R-squared:  0.405,	Adjusted R-squared:  0.403 
## F-statistic:  348 on 14 and 7168 DF,  p-value: &lt;2e-16
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e"># Check for colinearity</span>
<span style="color:#a6e22e">vif</span>(model5d)
</code></pre></div><pre><code>##                      GVIF Df GVIF^(1/(2*Df))
## prop_type_simplified 1.34  4            1.04
## log_numberofreview   1.16  1            1.08
## review_scores_rating 1.07  1            1.04
## room_type            1.40  3            1.06
## bathrooms            1.54  1            1.24
## bedrooms             2.34  1            1.53
## beds                 2.08  1            1.44
## host_is_superhost    1.21  1            1.10
## is_location_exact    1.01  1            1.01
</code></pre><p><code>is_location_exact</code> is only 1% statistically relevant when we consider it with only the property type, number of reviews and review score rating. When we also add room_type to that list, is becomes 5% statistically relevant and when we add in all the prior variables p increases to 0.037.</p>
<h2 id="model-6">Model 6</h2>
<p>For all cities, there are 3 variables that relate to neighbourhoods: <code>neighbourhood</code>, <code>neighbourhood_cleansed</code>, and <code>neighbourhood_group_cleansed</code>. There are typically more than 20 neighbourhoods in each city, and it wouldn’t make sense to include them all in our model.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">skim</span>(listings<span style="color:#f92672">$</span>neighbourhood_cleansed)
</code></pre></div><p>Table: Data summary</p>
<table>
<thead>
<tr>
<th style="text-align:left"></th>
<th style="text-align:left"></th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">Name</td>
<td style="text-align:left">listings$neighbourhood_cl&hellip;</td>
</tr>
<tr>
<td style="text-align:left">Number of rows</td>
<td style="text-align:left">7279</td>
</tr>
<tr>
<td style="text-align:left">Number of columns</td>
<td style="text-align:left">1</td>
</tr>
<tr>
<td style="text-align:left">_______________________</td>
<td style="text-align:left"></td>
</tr>
<tr>
<td style="text-align:left">Column type frequency:</td>
<td style="text-align:left"></td>
</tr>
<tr>
<td style="text-align:left">character</td>
<td style="text-align:left">1</td>
</tr>
<tr>
<td style="text-align:left">________________________</td>
<td style="text-align:left"></td>
</tr>
<tr>
<td style="text-align:left">Group variables</td>
<td style="text-align:left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left">skim_variable</th>
<th style="text-align:right">n_missing</th>
<th style="text-align:right">complete_rate</th>
<th style="text-align:right">min</th>
<th style="text-align:right">max</th>
<th style="text-align:right">empty</th>
<th style="text-align:right">n_unique</th>
<th style="text-align:right">whitespace</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">data</td>
<td style="text-align:right">0</td>
<td style="text-align:right">1</td>
<td style="text-align:right">5</td>
<td style="text-align:right">21</td>
<td style="text-align:right">0</td>
<td style="text-align:right">19</td>
<td style="text-align:right">0</td>
</tr>
</tbody>
</table>
<p>Using our city knowledge, we group neighbourhoods into 3 geographical areas.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">listings_selected<span style="color:#f92672">&lt;-</span>listings_selected <span style="color:#f92672">%&gt;%</span>
  <span style="color:#a6e22e">mutate</span>(neighbourhood_simplified <span style="color:#f92672">=</span> <span style="color:#a6e22e">case_when</span>(
      neighbourhood_cleansed <span style="color:#f92672">%in%</span> <span style="color:#a6e22e">c</span>(<span style="color:#e6db74">&#34;Jette&#34;</span>,<span style="color:#e6db74">&#34;Ganshoren&#34;</span>, <span style="color:#e6db74">&#34;Koekelberg&#34;</span>,<span style="color:#e6db74">&#34;Molenbeek-Saint-Jean&#34;</span>, <span style="color:#e6db74">&#34;Berchem-Sainte-Agathe&#34;</span>, <span style="color:#e6db74">&#34;Anderlecht&#34;</span>) <span style="color:#f92672">~</span> <span style="color:#e6db74">&#34;west_of_Bruxelles&#34;</span>,
      neighbourhood_cleansed <span style="color:#f92672">%in%</span> <span style="color:#a6e22e">c</span>(<span style="color:#e6db74">&#34;Saint-Gilles&#34;</span>,<span style="color:#e6db74">&#34;Forest&#34;</span>, <span style="color:#e6db74">&#34;Ixelles&#34;</span>,<span style="color:#e6db74">&#34;Uccle&#34;</span>, <span style="color:#e6db74">&#34;Watermael-Boitsfort&#34;</span>, <span style="color:#e6db74">&#34;Auderghem&#34;</span>) <span style="color:#f92672">~</span> <span style="color:#e6db74">&#34;south_of_Bruxelles&#34;</span>,
      neighbourhood_cleansed <span style="color:#f92672">%in%</span> <span style="color:#a6e22e">c</span>(<span style="color:#e6db74">&#34;Saint-Josse-ten-Noode&#34;</span>,<span style="color:#e6db74">&#34;Schaerbeek&#34;</span>, <span style="color:#e6db74">&#34;Evere&#34;</span>,<span style="color:#e6db74">&#34;Woluwe-Saint-Lambert&#34;</span>, <span style="color:#e6db74">&#34;Wolume-Saint-Pierre&#34;</span>, <span style="color:#e6db74">&#34;Etterbeek&#34;</span>) <span style="color:#f92672">~</span> <span style="color:#e6db74">&#34;east_of_Bruxelles&#34;</span>,
      <span style="color:#66d9ef">TRUE</span> <span style="color:#f92672">~</span> <span style="color:#e6db74">&#34;Bruxelles&#34;</span>
  ))
</code></pre></div><p>Next we add <code>neighbourhood_simplified</code> to our model to see whether location is a predictor of <code>price_4_nights</code>.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">model6 <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">lm</span>(<span style="color:#a6e22e">log</span>(price_4_nights) <span style="color:#f92672">~</span> prop_type_simplified <span style="color:#f92672">+</span> log_numberofreview <span style="color:#f92672">+</span> review_scores_rating <span style="color:#f92672">+</span> room_type <span style="color:#f92672">+</span> bathrooms <span style="color:#f92672">+</span> bedrooms <span style="color:#f92672">+</span> beds <span style="color:#f92672">+</span> host_is_superhost <span style="color:#f92672">+</span> neighbourhood_simplified, data <span style="color:#f92672">=</span> listings_selected)

<span style="color:#a6e22e">summary</span>(model6)
</code></pre></div><pre><code>## 
## Call:
## lm(formula = log(price_4_nights) ~ prop_type_simplified + log_numberofreview + 
##     review_scores_rating + room_type + bathrooms + bedrooms + 
##     beds + host_is_superhost + neighbourhood_simplified, data = listings_selected)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -5.959 -0.280 -0.015  0.242  4.340 
## 
## Coefficients:
##                                            Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                                 5.53678    0.06947   79.70  &lt; 2e-16
## prop_type_simplifiedCondominium             0.05941    0.02722    2.18  0.02910
## prop_type_simplifiedHouse                   0.04992    0.02034    2.45  0.01415
## prop_type_simplifiedOther                   0.30775    0.01904   16.17  &lt; 2e-16
## prop_type_simplifiedTownhouse               0.08137    0.02876    2.83  0.00468
## log_numberofreview                         -0.02165    0.00368   -5.88  4.3e-09
## review_scores_rating                        0.00276    0.00073    3.78  0.00016
## room_typeHotel room                         0.09345    0.05292    1.77  0.07750
## room_typePrivate room                      -0.54664    0.01304  -41.92  &lt; 2e-16
## room_typeShared room                       -0.79145    0.05637  -14.04  &lt; 2e-16
## bathrooms                                  -0.03814    0.01157   -3.30  0.00099
## bedrooms                                    0.15230    0.00980   15.55  &lt; 2e-16
## beds                                        0.07715    0.00598   12.91  &lt; 2e-16
## host_is_superhostTRUE                       0.14300    0.01553    9.21  &lt; 2e-16
## neighbourhood_simplifiedeast_of_Bruxelles  -0.19509    0.01648  -11.84  &lt; 2e-16
## neighbourhood_simplifiedsouth_of_Bruxelles -0.16462    0.01315  -12.51  &lt; 2e-16
## neighbourhood_simplifiedwest_of_Bruxelles  -0.20327    0.01969  -10.32  &lt; 2e-16
##                                               
## (Intercept)                                ***
## prop_type_simplifiedCondominium            *  
## prop_type_simplifiedHouse                  *  
## prop_type_simplifiedOther                  ***
## prop_type_simplifiedTownhouse              ** 
## log_numberofreview                         ***
## review_scores_rating                       ***
## room_typeHotel room                        .  
## room_typePrivate room                      ***
## room_typeShared room                       ***
## bathrooms                                  ***
## bedrooms                                   ***
## beds                                       ***
## host_is_superhostTRUE                      ***
## neighbourhood_simplifiedeast_of_Bruxelles  ***
## neighbourhood_simplifiedsouth_of_Bruxelles ***
## neighbourhood_simplifiedwest_of_Bruxelles  ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.463 on 7166 degrees of freedom
##   (3 observations deleted due to missingness)
## Multiple R-squared:  0.423,	Adjusted R-squared:  0.422 
## F-statistic:  328 on 16 and 7166 DF,  p-value: &lt;2e-16
</code></pre><p>Above results show location is a predictor of <code>price_4_nights</code>.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e"># Check for colinearity</span>
<span style="color:#a6e22e">vif</span>(model6)
</code></pre></div><pre><code>##                          GVIF Df GVIF^(1/(2*Df))
## prop_type_simplified     1.36  4            1.04
## log_numberofreview       1.18  1            1.08
## review_scores_rating     1.08  1            1.04
## room_type                1.41  3            1.06
## bathrooms                1.54  1            1.24
## bedrooms                 2.35  1            1.53
## beds                     2.09  1            1.45
## host_is_superhost        1.21  1            1.10
## neighbourhood_simplified 1.07  3            1.01
</code></pre><h2 id="model-7">Model 7</h2>
<p>We also add <code>cancellation_policy</code> to model, to see its effet on <code>price_4_nights</code></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">model7 <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">lm</span>(<span style="color:#a6e22e">log</span>(price_4_nights) <span style="color:#f92672">~</span> prop_type_simplified <span style="color:#f92672">+</span> log_numberofreview <span style="color:#f92672">+</span> review_scores_rating <span style="color:#f92672">+</span> room_type <span style="color:#f92672">+</span> bathrooms <span style="color:#f92672">+</span> bedrooms <span style="color:#f92672">+</span> beds <span style="color:#f92672">+</span> host_is_superhost <span style="color:#f92672">+</span> neighbourhood_simplified <span style="color:#f92672">+</span> cancellation_policy, data <span style="color:#f92672">=</span> listings_selected)

<span style="color:#a6e22e">summary</span>(model7)
</code></pre></div><pre><code>## 
## Call:
## lm(formula = log(price_4_nights) ~ prop_type_simplified + log_numberofreview + 
##     review_scores_rating + room_type + bathrooms + bedrooms + 
##     beds + host_is_superhost + neighbourhood_simplified + cancellation_policy, 
##     data = listings_selected)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -5.827 -0.278 -0.014  0.235  4.311 
## 
## Coefficients:
##                                                 Estimate Std. Error t value
## (Intercept)                                     5.492982   0.068732   79.92
## prop_type_simplifiedCondominium                 0.054647   0.026897    2.03
## prop_type_simplifiedHouse                       0.045115   0.020105    2.24
## prop_type_simplifiedOther                       0.300178   0.018837   15.94
## prop_type_simplifiedTownhouse                   0.077554   0.028423    2.73
## log_numberofreview                             -0.033779   0.003785   -8.92
## review_scores_rating                            0.002754   0.000721    3.82
## room_typeHotel room                             0.121987   0.053377    2.29
## room_typePrivate room                          -0.531660   0.012943  -41.08
## room_typeShared room                           -0.799265   0.055707  -14.35
## bathrooms                                      -0.037851   0.011436   -3.31
## bedrooms                                        0.150584   0.009681   15.55
## beds                                            0.075462   0.005906   12.78
## host_is_superhostTRUE                           0.138025   0.015349    8.99
## neighbourhood_simplifiedeast_of_Bruxelles      -0.190971   0.016293  -11.72
## neighbourhood_simplifiedsouth_of_Bruxelles     -0.156883   0.013014  -12.05
## neighbourhood_simplifiedwest_of_Bruxelles      -0.204064   0.019476  -10.48
## cancellation_policymoderate                     0.072682   0.013548    5.36
## cancellation_policystrict_14_with_grace_period  0.180950   0.013743   13.17
## cancellation_policysuper_strict_30             -0.241036   0.234370   -1.03
## cancellation_policysuper_strict_60              0.892970   0.457762    1.95
##                                                Pr(&gt;|t|)    
## (Intercept)                                     &lt; 2e-16 ***
## prop_type_simplifiedCondominium                 0.04222 *  
## prop_type_simplifiedHouse                       0.02486 *  
## prop_type_simplifiedOther                       &lt; 2e-16 ***
## prop_type_simplifiedTownhouse                   0.00638 ** 
## log_numberofreview                              &lt; 2e-16 ***
## review_scores_rating                            0.00014 ***
## room_typeHotel room                             0.02232 *  
## room_typePrivate room                           &lt; 2e-16 ***
## room_typeShared room                            &lt; 2e-16 ***
## bathrooms                                       0.00094 ***
## bedrooms                                        &lt; 2e-16 ***
## beds                                            &lt; 2e-16 ***
## host_is_superhostTRUE                           &lt; 2e-16 ***
## neighbourhood_simplifiedeast_of_Bruxelles       &lt; 2e-16 ***
## neighbourhood_simplifiedsouth_of_Bruxelles      &lt; 2e-16 ***
## neighbourhood_simplifiedwest_of_Bruxelles       &lt; 2e-16 ***
## cancellation_policymoderate                     8.4e-08 ***
## cancellation_policystrict_14_with_grace_period  &lt; 2e-16 ***
## cancellation_policysuper_strict_30              0.30378    
## cancellation_policysuper_strict_60              0.05113 .  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.457 on 7162 degrees of freedom
##   (3 observations deleted due to missingness)
## Multiple R-squared:  0.437,	Adjusted R-squared:  0.435 
## F-statistic:  278 on 20 and 7162 DF,  p-value: &lt;2e-16
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e"># Check for colinearity</span>
<span style="color:#a6e22e">vif</span>(model7)
</code></pre></div><pre><code>##                          GVIF Df GVIF^(1/(2*Df))
## prop_type_simplified     1.36  4            1.04
## log_numberofreview       1.27  1            1.13
## review_scores_rating     1.08  1            1.04
## room_type                1.48  3            1.07
## bathrooms                1.54  1            1.24
## bedrooms                 2.35  1            1.53
## beds                     2.09  1            1.45
## host_is_superhost        1.21  1            1.10
## neighbourhood_simplified 1.08  3            1.01
## cancellation_policy      1.20  4            1.02
</code></pre><p>Results show cancellation policy does act as a pricing premium. If the cancellation policy is moderate or strict_14_with_grace_period, the price is higher.</p>
<h2 id="best-model">Best Model</h2>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">huxreg</span>(model1,model2,model3b,model4b,model5d,model6,model7)
</code></pre></div><p>preserve584c1d173ef24df8</p>
<p>Model 7 is the best prediction model since it has the highest R-squared (0.437). This means 43.7% variance of dependent variable is explained by the independent variables in the model.</p>
<p>We also check the residuals and colinearity of the model. Results here by <code>autoplot</code> show residuals seem to obey normal distribution and results above show there&rsquo;s no colinearity problem.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">autoplot</span>(model7)
</code></pre></div><p><!-- raw HTML omitted --></p>
<h1 id="prediction-and-conclusion">Prediction and Conclusion</h1>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">newdata<span style="color:#f92672">=</span><span style="color:#a6e22e">data.frame</span>(prop_type_simplified<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;Apartment&#34;</span>,    log_numberofreview<span style="color:#f92672">=</span><span style="color:#ae81ff">2.3979</span>,
    review_scores_rating<span style="color:#f92672">=</span><span style="color:#ae81ff">90</span>, room_type<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;Private room&#34;</span>,
    bathrooms<span style="color:#f92672">=</span><span style="color:#ae81ff">2</span>, bedrooms<span style="color:#f92672">=</span><span style="color:#ae81ff">3</span>, beds<span style="color:#f92672">=</span><span style="color:#ae81ff">4</span>,
    accommodates<span style="color:#f92672">=</span><span style="color:#ae81ff">6</span>, host_is_superhost<span style="color:#f92672">=</span><span style="color:#66d9ef">TRUE</span>,
    is_location_exact<span style="color:#f92672">=</span><span style="color:#66d9ef">TRUE</span>, neighbourhood_simplified <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;Bruxelles&#34;</span>,
    cancellation_policy<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;strict_14_with_grace_period&#34;</span>)
  
<span style="color:#a6e22e">exp</span>(<span style="color:#a6e22e">predict</span>(model7,newdata <span style="color:#f92672">=</span> newdata, interval<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;confidence&#34;</span>))
</code></pre></div><pre><code>##   fit lwr upr
## 1 457 435 481
</code></pre>
                        </div>
                    </section>
            <!-- Disqus Inject -->
                
            </div>
            
        <!-- Footer -->
            
                <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <ul class="icons">
                
                    <li><a href="https://www.twitter.com" class="icon alt fa-twitter" target="_blank"><span class="label">Twitter</span></a></li>
                
                    <li><a href="https://www.facebook.com" class="icon alt fa-facebook" target="_blank"><span class="label">Facebook</span></a></li>
                
                    <li><a href="https://www.instagram.com" class="icon alt fa-instagram" target="_blank"><span class="label">Instagram</span></a></li>
                
                    <li><a href="https://www.github.com" class="icon alt fa-github" target="_blank"><span class="label">GitHub</span></a></li>
                
                    <li><a href="https://www.linkedin.com" class="icon alt fa-linkedin" target="_blank"><span class="label">LinkedIn</span></a></li>
                
            </ul>
            <ul class="copyright">
                <li>&copy; Company Name</li>
                
                <li>Design:  <a href="https://www.html5up.net">HTML5 UP</a></li>
                
            </ul>
        </div>
    </footer>

            
        </div>

    <!-- Scripts -->
        <!-- Scripts -->
    <!-- jQuery -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/jquery.scrolly.min.js"></script>
    <script src="/js/jquery.scrollex.min.js"></script>
    <script src="/js/skel.min.js"></script>
    <script src="/js/util.js"></script>

    

    <!-- Main JS -->
    <script src="/js/main.js"></script>

    

    

    </body>
</html>
